CREATE TABLE storyView (
    storyId INTEGER NOT NULL REFERENCES story(storyId) ON DELETE CASCADE,
    userId TEXT NOT NULL REFERENCES user(userId) ON DELETE CASCADE,
    viewedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (storyId, userId)
);

CREATE INDEX storyView_userId ON storyView (userId);
