ALTER TABLE user ADD COLUMN showWebsite INTEGER NOT NULL DEFAULT 1;
ALTER TABLE user ADD COLUMN showContactEmail INTEGER NOT NULL DEFAULT 1;
ALTER TABLE user ADD COLUMN showPhone INTEGER NOT NULL DEFAULT 1;
